version: "3.8"

services:
  century-frontend:
    image: nginx:latest
    container_name: century-frontend
    labels:
      - "loki.enable=true"
      - "loki.format=nginx"
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - century_network

  frontend-promtail:
    image: grafana/promtail:2.9.5
    container_name: frontend-promtail
    volumes:
      - ./promtail/promtail-frontend-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - century_network
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    networks:
      - century_network
    restart: unless-stopped
    command: -nginx.scrape-uri=http://century-frontend:80/nginx_status
    depends_on:
      - century-frontend

  # frontend-node-exporter:
  #   image: prom/node-exporter:v1.7.0
  #   container_name: frontend-node-exporter
  #   ports:
  #     - "9100:9100"
  #   networks:
  #     - century_network
  #   restart: unless-stopped
  #   pid: "host"
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--path.rootfs=/rootfs'

networks:
  century_network:
    external: true