global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "/etc/prometheus/rules/*.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'spring-boot'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['century-backend:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: nginx_frontend

  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis-master-1-exporter'
    static_configs:
      - targets: ['redis-master-1-exporter:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis-master-2-exporter'
    static_configs:
      - targets: ['redis-master-2-exporter:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis-master-3-exporter'
    static_configs:
      - targets: ['redis-master-3-exporter:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'century-backend-1'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['century-backend-1:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'century-backend-2'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['century-backend-2:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'century-backend-3'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['century-backend-3:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis-slave-1-exporter'
    static_configs:
      - targets: ['redis-slave-1:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis-slave-2-exporter'
    static_configs:
      - targets: ['redis-slave-2:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis-slave-3-exporter'
    static_configs:
      - targets: ['redis-slave-3:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'app-node-exporter'
    static_configs:
      - targets: ['app-node-exporter:9100']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'frontend-node-exporter'
    static_configs:
      - targets: ['frontend-node-exporter:9100']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'backend-node-exporter'
    static_configs:
      - targets: ['backend-node-exporter:9100']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # - job_name: 'db-node-exporter'
  #   static_configs:
  #     - targets: ['db-node-exporter:9100']
  #   metrics_path: /metrics
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance

  # - job_name: 'redis-node-1-exporter'
  #   static_configs:
  #     - targets: ['redis-node-1-exporter:9100']
  #   metrics_path: /metrics
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance

  # - job_name: 'redis-node-2-exporter'
  #   static_configs:
  #     - targets: ['redis-node-2-exporter:9100']
  #   metrics_path: /metrics
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance

  # - job_name: 'redis-node-3-exporter'
  #   static_configs:
  #     - targets: ['redis-node-3-exporter:9100']
  #   metrics_path: /metrics
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance

  # - job_name: 'opnsense'
  #   static_configs:
  #     - targets: ['OPNSENSE-IP:9100']    
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance