# 기본 설정 파일 - 공통 설정만 포함
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:noredis}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    timezone: GMT+9

  jpa:
    hibernate:
      ddl-auto: update  # DB 스키마 자동 업데이트
    show-sql: true      # SQL 쿼리 로깅 활성화
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅

  mvc:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true

server:
  port: 8080           # 서버 포트 번호
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: ${JWT_SECRET}  # JWT 시크릿 키 (환경변수 우선, 기본값 없음)
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRE_TIME:3600000}  # 액세스 토큰 유효기간 (밀리초 단위)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRE_TIME:86400000}  # 리프레시 토큰 유효기간 (밀리초 단위)

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: century-backend 
